allwinner: Add BL32(corresponds to Trusted OS) support
Andre-ARM/arm-trusted-firmware pull request #2
Opened 2018-05-25 08:13 UTC by Amit-Radur

This patch is an attempt to run Trusted OS(OPTEE-OS being one of them) along
side BL31 image.

ATF supports multiple SPD's that can take dispatcher name(opteed for OPTEE-OS)
as an input using the 'SPD=<dispatcher name>' option during bl31 build.

Signed-off-by: Amit Singh Tomar <amittomer25@gmail.com>

2018-05-25 14:19 UTC, Andre-ARM requested changes
- So who does protect the memory for the secure OS? Is that ATF's duty or is this meant to be done by OPT-EE OS, for instance?
- This will probably fail horribly if there is nothing at this address. I take it it's the duty of the loader (U-Boot's SPL in our case) to put some sensible code there, but what if this didn't happen? If possible, I would like to keep this one-ATF-image approach, so can we somehow check that there has been something loaded into DRAM? Maybe OPTEE-OS has some magic we can check?

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/common/include/platform_def.h
> +#define BL32_BASE                   SUNXI_DRAM_BASE
Is there any reason this needs to be set here? I would suggest:
```
#ifndef SPD_none
#ifndef BL32_BASE
#define BL32_BASE        SUNXI_DRAM_BASE
#endif
#endif
```

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/common/sunxi_bl31_setup.c
> +#include <plat_arm.h>
I don't think this is needed.

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/common/sunxi_bl31_setup.c
> +	bl32_image_ep_info.spsr = arm_get_spsr_for_bl32_entry();
According to the comment in the definition of this function this is not needed: https://github.com/Andre-ARM/arm-trusted-firmware/blob/f11916bf1dfecd7ee76240eebd847681ce366a67/plat/arm/common/arm_common.c#L108-L118

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/common/sunxi_bl31_setup.c
> +	SET_SECURITY_STATE(bl33_image_ep_info.h.attr, NON_SECURE);
Please don't move this around needlessly.

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/common/sunxi_bl31_setup.c
> +	else if (type == SECURE && bl32_image_ep_info.pc)
The "else" is not needed.

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/sun50i_a64/platform.mk
> +				plat/arm/common/arm_common.c \
This looks wrong, also is not needed anymore.

2018-05-25 14:19 UTC, Andre-ARM commented on plat/allwinner/common/include/platform_def.h
> +#define PLAT_ARM_NS_IMAGE_OFFSET    0x4a000000
Please indent the value with tabs to align with the other definitions.

2018-05-25 15:23 UTC, Amit-Radur commented on plat/allwinner/common/sunxi_bl31_setup.c
> +	bl32_image_ep_info.spsr = arm_get_spsr_for_bl32_entry();
Ok, you mean we need not to fill bl32_image_ep_info.spsr via arm_get_spsr_for_bl32_entry ?

2018-05-25 15:24 UTC, Amit-Radur commented on plat/allwinner/common/include/platform_def.h
> +#define PLAT_ARM_NS_IMAGE_OFFSET    0x4a000000
ok.

2018-05-25 15:28 UTC, Amit-Radur commented on plat/allwinner/common/include/platform_def.h
> +#define BL32_BASE                   SUNXI_DRAM_BASE
Wanted to set BL32_BASE only in case of SPD has been used.

2018-05-25 15:48 UTC, Amit-Radur commented
So who does protect the memory for the secure OS? Is that ATF's duty or is this meant to be done by OPT-EE OS, for instance?
 
[Amit]: AFAIK, ideally, it should be done by the loader(could be running SPL or ATF running at EL3), prior to OP-TEE .

 This will probably fail horribly if there is nothing at this address. I take it it's the duty of the loader (U-Boot's SPL in our case) to put some sensible code there, but what if this didn't happen? If possible, I would like to keep this one-ATF-image approach, so can we somehow check that there has been something loaded into DRAM? Maybe OPTEE-OS has some magic we can check?

[Amit]: Yes, OPTEE-OS has the specific header but it would need a parser in ATF. At the moment  I just tested with raw arm executable provided by the OPTEE-OS build system(tee-pager_v2.bin).

2018-05-29 10:24 UTC, Andre-ARM commented
* Re: OPTEE-OS header parsing:
I don't think that's the right approach. The "OTPE" header is just meant for the *loader*, so U-Boot's SPL in our case. This loader is meant to parse the header and load the raw binary to the location specified in this very header. So the magic number is not there anymore in memory. You can easily see that this can't work since the header starts with the magic and this is not a valid AArch64 instruction.
Can you check what Rockchip does in U-Boot/ATF to communicate loaded payloads? I believe they have something in place to let ATF know what the loaded did.
* Re: Secure memory setup:
Since ATF can't be bothered with knowing how much memory the secure payload is going to need, I guess it's up to BL32/OPTEE-OS to secure the memory. The TZC is memory mapped, and since BL32 is also running secure, I can't see why programming it should not work. Just need to figure out how the two (BL31 and OPTEE-OS) would coordinate over this. Again looking at existing examples (Juno? Rockchip?) would probably be helpful.

2018-06-02 19:13 UTC, Amit-Radur commented
Re:Secure memory setup:
You're right about it. Now, could program TZC/SMC from OPTEE-OS itself running in Secure EL1.
But what about the SPC block, it anyways needed to be programmed in ATF and should we re-progarm it in OPTEE-OS ?

"Just need to figure out how the two (BL31 and OPTEE-OS) would coordinate over this"
I didn't get why it would be needed ?

2018-06-04 08:30 UTC, closed without merging